#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTSMUX,         sensorI2CCustom)
#pragma config(Sensor, S4,     LEGOUS,         sensorSONAR)
#pragma config(Motor,  motorA,          flipperLift,   tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     rightMotor,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     leftMotor,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     sweep,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     lift,          tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C1_1,    grabber1,             tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    grabber2,             tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    dumper,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    stickcontrol,         tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C1_5,    flipperControl1,      tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    flipperControl2,      tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int hitter=1;
int speed, xspeed, threshold=10;
int flipperLiftVar=1;
int liftMult;
int flipperPosition=1;
#include "functions.h"
#include "gyroturn.h"
#include "lego-ultrasound.h"
#include "JoystickDriver.c"
#include "lego-touch.h"

const tMUXSensor LEGOTOUCH = msensor_S2_3;
//#define LEGOUS msensor_S2_2
//#define forward msensor_S2_2


task main()
{

	time1[T2]=0;
	waitForStart();
	nMotorEncoder[flipperLift]=0;
	servo[stickcontrol]=128;
	while(true)                            // Infinite loop:
	{

		getJoystickSettings(joystick);

		if(joy2btn(4)==1&&time1[T4]>1000){
			flipperPosition*=-1;
			time1[T4]=0;
		}

		if(flipperPosition==1){
			servo[flipperControl1]=225;
			servo[flipperControl2]=0;
		}
		else{
			servo[flipperControl1]=105;
			servo[flipperControl2]=120;
		}



		if(abs(joystick.joy1_x2)>threshold){ //gets the ammount of turn from the joystick, but insted of directly taking it
			xspeed=(joystick.joy1_x2/1.3);
			}else{
			xspeed=0;
		}


		if(abs(joystick.joy1_y2)>threshold){ //get the speed from the joystick
			speed=joystick.joy1_y2/1.3;
			}else{
			speed=0;
		}

		if(joy1Btn(7)==1){
			speed /=10;
			xspeed /=15;
		}

		motor[rightMotor]=(speed-xspeed); //speed is offset so we can turn, then is fed to the motors
		motor[leftMotor]=(speed+xspeed);

		getJoystickSettings(joystick);

/*		if(time1[T2]>500&&joy1Btn(3)==1){ //center hitter
			hitter = hitter*-1;
			time1[T2]=0;
			if(time1[T2]<900){
				servo[stickcontrol]= 128*hitter+128;
			}
		}

		if(time1[T2]>900==1){
			servo[stickcontrol]=128;
			time1[T2]=0;
		}
*/
		if(joy1Btn(3)==1) {
			while(joy1Btn(3)==1) {
				servo[stickcontrol]=200;
			}
			servo[stickcontrol]=128;
		}
		if(joy1Btn(2)==1) {
			while(joy1Btn(2)==1) {
				servo[stickcontrol] = 50;
			}
			servo[stickcontrol]=128;
		}

		if(TSreadState(LEGOTOUCH)==1) nMotorEncoder(lift)=0;

		if(joy2Btn(7)==1) liftMult=4;
		if(abs(nMotorEncoder(lift))<500&&joystick.joy2_y1<0) liftMult=10;
		else liftMult=1.3;

		if (abs(joystick.joy2_y1) > threshold) { //all of this bit says that if the joystick is up, the lift goes up
			if (TSreadState(LEGOTOUCH) == 0) { //and if the joy is down, and the lift isn't at the bottom the lift goes down
				motor[lift]=joystick.joy2_y1 / liftMult;
			}
			else if ((TSreadState(LEGOTOUCH) == 1) && (joystick.joy2_y1>0||joy2Btn(2)==1)) {
				motor[lift]=joystick.joy2_y1 / liftMult;
			}
			else motor[lift] = 0;
		}
		else motor[lift] = 0;


		getJoystickSettings(joystick);
		if(joy1Btn(5)==1){ //if a button is pressed it pulls the grabber up, otherwise it grabs
			servo[grabber1]=45;
			servo[grabber2]=182;
			}else{ //down
			servo[grabber1]=5;
			servo[grabber2]=222;
		}

		getJoystickSettings(joystick);
		if(joy2Btn(8)==1){ //if a button is pressed it dumps
			servo[dumper]=0;
			}else{ //down
			servo[dumper]=190;
		}

		getJoystickSettings(joystick);
		if(joy2Btn(6) == 1&&(TSreadState(LEGOTOUCH) == 1||joy2Btn(2)==1)) {
			motor[sweep]=100;
		}
		else if(joy2Btn(5) == 1){
			motor[sweep] = -50;
		}
		else{
			motor[sweep] = 0;
		}

		if(joy1Btn(1) == 1 && time1[T3]>500){
			tHTIRS2 irRight;
			tHTIRS2 irLeft;
			initSensor(&irRight, msensor_S2_4);
			initSensor(&irLeft, msensor_S3_2);
			irRight.mode = DSP_1200;
			irLeft.mode = DSP_1200;
			time1[T3]=0;
			while(SensorValue(LEGOUS) > 25 && joy1Btn(1)!=1 || time1[T3]<500) {
				readSensor(&irRight);
				nxtDisplayTextLine(1, "IR: %d", irRight.acDirection);
				int right = irRight.acDirection;
				int dif = (4-right)*6

				motor[leftMotor]=-10-dif;
				motor[rightMotor]=-10+dif;
			}
		time1[T3]=0;

		motor[leftMotor] = 0;
		motor[rightMotor] = 0;
	}

}
}
