#pragma config(Sensor, S2,     HTSMUX,         sensorI2CCustom9V)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "common.h"
#include "hitechnic-sensormux.h"
#include "lego-touch.h"
const tMUXSensor LEGOTOUCH = msensor_S2_3;

task main(){
	while(true){
		int x = TSreadState(LEGOTOUCH);
		displayCenteredBigTextLine(3, "%d", x);
		sleep(10);
	}
}
